### ISSUE TITLE
Building on Linux

### ISSUE THREAD

**Issue by d4rkd0s** [FredHutch/Oncoscape#236]
When building on linux following the README.md I get the following issue, I think its related to the node/nodejs package name issues...

```
user@computer oncoscape/server/ # npm install

> rstats@0.3.1 install /home/user/Development/Oncoscape/server/node_modules/rstats
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.10.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/user/Development/Oncoscape/server/node_modules/rstats/.node-gyp"
make: Entering directory `/home/user/Development/Oncoscape/server/node_modules/rstats/build'
  CXX(target) Release/obj.target/R/src/rl.o
  CXX(target) Release/obj.target/R/src/rlink.o
  SOLINK_MODULE(target) Release/obj.target/R.node
/usr/bin/ld: cannot find -llzma
/usr/bin/ld: cannot find -lbz2
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/R.node] Error 1
make: Leaving directory `/home/user/Development/Oncoscape/server/node_modules/rstats/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.2.0-25-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/Development/Oncoscape/server/node_modules/rstats
gyp ERR! node -v v5.10.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN oncoscape@15.0.0 No repository field.
npm ERR! Linux 4.2.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! rstats@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rstats@0.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rstats package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rstats
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rstats
npm ERR! There is likely additional logging output above.

```

**Comment by d4rkd0s** [comment]
Regarding `Make sure you have the latest version of node.js and npm installed`

Here is the output of `sudo apt-get install nodejs npm`

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nodejs : Conflicts: npm
E: Unable to correct problems, you have held broken packages.
```

**Comment by mzager** [comment]
@d4rkd0s 
Perhaps this has something to do with the dev dependencies section located in the /server/package.json file.  I would recommend removing this section any trying again.  We will work on removing it from the dev environment now.

Specifically I would remove this section of the JSON and try running NPM install again.
"devDependencies": {
    "pdfkit": "^0.7.2",
    "rstats": "file:rstats"
  },

Thank you for your interest in Oncoscape

**Comment by d4rkd0s** [comment]
Will do, thank you @mzager

**Comment by d4rkd0s** [comment]
New output...

```
10:44 $ npm install

> rstats@0.3.1 install /home/user/Development/Oncoscape/server/rstats
> node-gyp rebuild

make: Entering directory `/home/user/Development/Oncoscape/server/rstats/build'
  CXX(target) Release/obj.target/R/src/rl.o
  CXX(target) Release/obj.target/R/src/rlink.o
  SOLINK_MODULE(target) Release/obj.target/R.node
/usr/bin/ld: cannot find -llzma
/usr/bin/ld: cannot find -lbz2
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/R.node] Error 1
make: Leaving directory `/home/user/Development/Oncoscape/server/rstats/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.2.0-25-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/Development/Oncoscape/server/rstats
gyp ERR! node -v v5.10.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

npm WARN rstats@0.3.1 license should be a valid SPDX license expression
npm ERR! Linux 4.2.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! rstats@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rstats@0.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rstats package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rstats
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rstats
npm ERR! There is likely additional logging output above.
```

**Comment by d4rkd0s** [comment]
Followed the entire INSTALL.md over again this time before building anything I updated the packages.json in server/ just as you asked. Now I have different output, any ideas? @mzager

**Comment by mzager** [comment]
@d4rkd0s Would you mind sending me the linux build / version number you are using?  I can try it in a docker container and see what it gives me.  We are not seeing any errors using Ubuntu 14.04.  

Also out of curiousity what happens when you try doing an npm install in the <path>/Oncoscape/Server/Rstats folder? 

I'm a little surprised that calling npm install in the server folder references RStats.  The connection between node and R is the area in which we have experienced the most trouble.

**Comment by d4rkd0s** [comment]
Output from `npm install` under `Oncoscape/Server/Rstats`:

```
14:59 $ npm install

> rstats@0.3.1 install /home/user/Development/Oncoscape/server/rstats
> node-gyp rebuild

make: Entering directory `/home/user/Development/Oncoscape/server/rstats/build'
  CXX(target) Release/obj.target/R/src/rl.o
  CXX(target) Release/obj.target/R/src/rlink.o
  SOLINK_MODULE(target) Release/obj.target/R.node
/usr/bin/ld: cannot find -llzma
/usr/bin/ld: cannot find -lbz2
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/R.node] Error 1
make: Leaving directory `/home/user/Development/Oncoscape/server/rstats/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.2.0-25-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/Development/Oncoscape/server/rstats
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

npm WARN rstats@0.3.1 license should be a valid SPDX license expression
npm ERR! Linux 4.2.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! rstats@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rstats@0.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rstats package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rstats
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rstats
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/Development/Oncoscape/server/rstats/npm-debug.log

```

**Comment by d4rkd0s** [comment]
![states for github issue](https://cloud.githubusercontent.com/assets/2348814/14330958/a8a8a72a-fc08-11e5-9f32-0c0d5f2e1de1.png)

**Comment by d4rkd0s** [comment]
I do want to work on the project very much so, I appreciate your time in troubleshooting this with me. :smiley_cat:

**Comment by d4rkd0s** [comment]
Here is my debug/log file
[npm-debug.txt](https://github.com/FredHutch/Oncoscape/files/207247/npm-debug.txt)

**Comment by d4rkd0s** [comment]
Here is my debug/log file
[npm-debug.txt](https://github.com/FredHutch/Oncoscape/files/207247/npm-debug.txt)

**Comment by mzager** [comment]
@d4rkd0s We will build a docker container tomorrow with this version and get back to you shortly.  Thank you again for your interest!

**Comment by GalaticStryder** [comment]
@d4rkd0s Can you check if lzma and bz2 compression tools are installed?

**Comment by mzager** [comment]
@d4rkd0s were you able to try @GalaticStryder's recommendation?  I attempted to get Oncoscape running on Mint yesterday and also ran into some trouble.  A college is going to take a look and we will get back to you shortly.  Thanks for your patience as we work through it.

**Comment by d4rkd0s** [comment]
@GalaticStryder Looks like they are both installed and available. @mzager 
```
user@computer ~/Development $ lzma
lzma: Compressed data cannot be written to a terminal
lzma: Try `lzma --help' for more information.
user@computer ~/Development $ bzip2
bzip2: I won't write compressed data to a terminal.
bzip2: For help, type: `bzip2 --help'.
```

**Comment by GalaticStryder** [comment]
But LD requires the lib, not the actual package as is.
I'm on Fedora 23, mine is xz-devel and bzip2-devel packages. Anyway, try this for apt based package managers:
sudo apt-get install libbz2-dev
sudo apt-get install liblzma-dev

**Comment by d4rkd0s** [comment]
@GalaticStryder looking better, will try again now.
```
user@computer # sudo apt-get install libbz2-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  libbz2-dev
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 33.2 kB of archives.
After this operation, 117 kB of additional disk space will be used.
Get:1 http://cosmos.cites.illinois.edu/pub/ubuntu/ trusty/main libbz2-dev amd64 1.0.6-5 [33.2 kB]
Fetched 33.2 kB in 0s (127 kB/s)    
Selecting previously unselected package libbz2-dev:amd64.
(Reading database ... 229114 files and directories currently installed.)
Preparing to unpack .../libbz2-dev_1.0.6-5_amd64.deb ...
Unpacking libbz2-dev:amd64 (1.0.6-5) ...
Setting up libbz2-dev:amd64 (1.0.6-5) ...
user@computer # sudo apt-get install liblzma-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  liblzma-doc
The following NEW packages will be installed:
  liblzma-dev
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 137 kB of archives.
After this operation, 644 kB of additional disk space will be used.
Get:1 http://cosmos.cites.illinois.edu/pub/ubuntu/ trusty/main liblzma-dev amd64 5.1.1alpha+20120614-2ubuntu2 [137 kB]
Fetched 137 kB in 0s (442 kB/s)     
Selecting previously unselected package liblzma-dev:amd64.
(Reading database ... 229118 files and directories currently installed.)
Preparing to unpack .../liblzma-dev_5.1.1alpha+20120614-2ubuntu2_amd64.deb ...
Unpacking liblzma-dev:amd64 (5.1.1alpha+20120614-2ubuntu2) ...
Setting up liblzma-dev:amd64 (5.1.1alpha+20120614-2ubuntu2) ...
user@computer #
```

**Comment by d4rkd0s** [comment]
We have success! Thank you @GalaticStryder :smiley: I am thinking of adding the following to INSTALL.md @mzager :


*NOTE:* When installing on certain distros of linux, (e.g. Linux Mint) you will have to ensure the **xz-devel** and **bzip2-devel** packages are installed.

Using **apt-get**:
```
sudo apt-get install libbz2-dev
sudo apt-get install liblzma-dev
```

**Comment by d4rkd0s** [comment]
`Error: Cannot find module './rstats/build/Release/R.node'` 
@mzager should I be adding back into `/server/packages.json` :

```
"devDependencies": {
"pdfkit": "^0.7.2",
"rstats": "file:rstats"
},
```

**Comment by mzager** [comment]
That's great news.  At this point you just need to execute the following;

cd /<path>/Oncoscape/server/rstats
npm install

**Comment by robert-mcdermott** [comment]
@mzager even after installing those packages (libbz2-dev and liblzma-dev) npm install in the server directory still fails on Mint 7.3:

```
OncoMint server # npm install

> rstats@0.3.1 install /root/Oncoscape/server/node_modules/rstats
> node-gyp rebuild

make: Entering directory `/root/Oncoscape/server/node_modules/rstats/build'
  CXX(target) Release/obj.target/R/src/rl.o
  CXX(target) Release/obj.target/R/src/rlink.o
  SOLINK_MODULE(target) Release/obj.target/R.node
/usr/bin/ld: cannot find -lpcre
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/R.node] Error 1
make: Leaving directory `/root/Oncoscape/server/node_modules/rstats/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.19.0-32-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/Oncoscape/server/node_modules/rstats
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN oncoscape@15.0.0 No repository field.
npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! rstats@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rstats@0.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rstats package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rstats
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rstats
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/Oncoscape/server/npm-debug.log
```

**Comment by GalaticStryder** [comment]
@robert-mcdermott You need to install some libs that the linker couldn't find in ur system. 
sudo apt-get install apt-file
sudo apt-file update
apt-file search /libpcre.a
apt-file search /libz.a
This will give you the packages that contain those libs and you just need to install 'em.
For Fedora: pcre-devel and lz4-devel. I don't know the package names for Debian/Ubuntu, sorry.

**Comment by robert-mcdermott** [comment]
@GalaticStryder Thanks, that led me to installing the missing packages: 

```
apt-get install -y libpcre3-dev libx32z1-dev zlib1g-dev
```

But it still doesn't work:

```
OncoMint server # npm install

> rstats@0.3.1 install /root/Oncoscape/server/node_modules/rstats
> node-gyp rebuild

make: Entering directory `/root/Oncoscape/server/node_modules/rstats/build'
  CXX(target) Release/obj.target/R/src/rl.o
  CXX(target) Release/obj.target/R/src/rlink.o
  SOLINK_MODULE(target) Release/obj.target/R.node
/usr/bin/ld: cannot find -lblas
/usr/bin/ld: cannot find -llapack
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/R.node] Error 1
make: Leaving directory `/root/Oncoscape/server/node_modules/rstats/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.19.0-32-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/Oncoscape/server/node_modules/rstats
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN oncoscape@15.0.0 No repository field.
npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! rstats@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rstats@0.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rstats package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rstats
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rstats
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/Oncoscape/server/npm-debug.log
```

Oncoscape builds, installs and runs on Ubuntu 14.04 just fine, which appears to be what Mint 7.3 is built on so I'm not sure why Mint doesn't work for me. I'm glad that some were able to get it working on Mint but I'm giving up on getting it working on Mint, sorry.

**Comment by GalaticStryder** [comment]
Don't you wonder why Mint is so snappy and lightweight? They cut off unneeded libs, packages... Al errors in your build aren't related to Mint or whatever but only missing components.

`/usr/bin/ld: cannot find -lblas
/usr/bin/ld: cannot find -llapack
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/R.node] Error 1`

This is the error, you just need to Google what ships those linker needed libs. It's a little more effort than regular Ubuntu compilation.

**Comment by sdelrio** [comment]
Try installing libblas and liblapack development library:
```
sudo apt-get install libblas-dev liblapack-dev
```

**Comment by d4rkd0s** [comment]
Closing this issue as much important information has been posted. It is now up to someone to publish this information in proper docs / README / INSTALL guide.

**Comment by mzager** [comment]
Just wanted to check in and see how things are going.  Let us know if there is anything we can do to help.

**Comment by d4rkd0s** [comment]
I am doing fine, tied up in other dev projects. I will attempt to join back in development on Oncoscape this summer sometime! Thanks for all the help @mzager
